name: Release
on:
    push:
        branches:
            - alpha
            - beta
            - rc
            - main
            - canary

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            issues: write
            pull-requests: write
            id-token: write
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v3
              with:
                  version: 8
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"
            - run: pnpm install
            - run: pnpm install semantic-release-config-techor --workspace-root
            - run: pnpm build
            - run: |
                for dir in packages/*/; do
                    cp README.md "$dir"
                done
            - uses: lewagon/wait-on-check-action@v1.3.3
              with:
                  ref: ${{ github.ref }}
                  running-workflow-name: wait-for-check-regexp
                  # todo: example-check
                  check-regexp: lint|test|commit-check|type-check|e2e
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  wait-interval: 10
            - run: pnpm exec semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
